"use client"

import { useState } from "react"
import { ArrowRight, CalendarDays, MapPin, Menu, Phone, X } from "lucide-react"

const services = [
  ["The Signature Cut", "Precision cut, wash & finish", "45 min", "€48"],
  ["Cut & Beard", "A complete reset from top to chin", "60 min", "€62"],
  ["The Classic Shave", "Hot towel, straight razor & calm", "30 min", "€38"],
  ["Father & Son", "A chair for both of you", "60 min", "€70"],
]
const barbers = [
  ["Milo van Dijk", "FOUNDING BARBER", "The precise one. Milo brings 14 years of European barbering to every chair."],
  ["Jules Bakker", "TEXTURE & SHAPE", "For the undone, the curly and everything that refuses to sit still."],
  ["Amara de Wit", "CLASSIC SHAVES", "Quiet hands, a steady razor, and an encyclopedic knowledge of good coffee."],
  ["Raf Smit", "MODERN CUTS", "The newest eye at CUT / THRU. Clean lines and a little left of centre."],
]
const testimonials = [
  ["“The best cut I’ve had in Amsterdam. The room is calm, the team is exact, and I left feeling like myself — just sharper.”", "— TOMAS R., DE PIJP"],
  ["“No small talk required, though the conversation is always good. This place understands that a haircut can be a ritual.”", "— ELLA M., OOST"],
  ["“Finally somewhere that treats a shave as more than an add-on. Beautiful details from door to mirror.”", "— NICK J., CENTRUM"],
]

export default function Page() {
  const [menu, setMenu] = useState(false)
  const [booking, setBooking] = useState(false)
  const [sent, setSent] = useState(false)
  return <main>
    <header className="fixed top-0 z-20 flex w-full items-center justify-between px-5 py-5 mix-blend-difference text-paper md:px-10">
      <a href="#top" className="text-sm font-bold tracking-[.28em]">CUT / THRU</a>
      <nav className="hidden items-center gap-8 text-xs uppercase tracking-[.16em] md:flex"><a href="#services">Services</a><a href="#barbers">Barbers</a><a href="#story">Our story</a><a href="#visit">Visit</a></nav>
      <button aria-label="Open menu" onClick={() => setMenu(!menu)} className="md:hidden"><Menu size={22}/></button>
      <button onClick={() => setBooking(true)} className="hidden border border-paper/50 px-4 py-2 text-xs uppercase tracking-[.16em] transition hover:bg-paper hover:text-ink md:block">Book now</button>
    </header>
    {menu && <div className="fixed inset-0 z-10 flex flex-col justify-center gap-7 bg-ink px-6 text-4xl display md:hidden"><button className="absolute right-5 top-5" onClick={() => setMenu(false)}><X/></button><a href="#services" onClick={() => setMenu(false)}>Services</a><a href="#barbers" onClick={() => setMenu(false)}>Barbers</a><a href="#story" onClick={() => setMenu(false)}>Our story</a><a href="#visit" onClick={() => setMenu(false)}>Visit</a></div>}
    <section id="top" className="film flex min-h-[90vh] flex-col justify-end px-5 pb-12 pt-32 md:min-h-screen md:px-10 md:pb-16"><div className="max-w-5xl"><p className="mb-5 text-xs uppercase tracking-[.25em] text-paper/70">Amsterdam · Since 2014</p><h1 className="display max-w-4xl text-[clamp(4rem,12vw,10rem)] leading-[.86] tracking-[-.05em]">Good hair.<br/><em>Good energy.</em></h1><div className="mt-10 flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><p className="max-w-xs text-sm leading-6 text-paper/75">A considered barbershop for modern Amsterdam. Precision cuts, classic shaves, no rush.</p><button onClick={() => setBooking(true)} className="flex w-fit items-center gap-8 bg-copper px-5 py-4 text-xs font-bold uppercase tracking-[.15em] text-ink">Book an appointment <ArrowRight size={16}/></button></div></div></section>
    <section className="paper px-5 py-20 md:px-10 md:py-32"><div className="mx-auto grid max-w-6xl gap-12 md:grid-cols-2 md:gap-24"><p className="text-xs font-bold uppercase tracking-[.2em] text-copper">The chair is yours</p><div><h2 className="display text-4xl leading-tight md:text-6xl">Not just a haircut.<br/><em>A moment to reset.</em></h2><p className="mt-8 max-w-md text-base leading-7 text-ink/70">CUT / THRU is a small, independent barbershop in the heart of Amsterdam. We make space for the details — the right shape, the right conversation, and a little time out of your day.</p><a href="#story" className="mt-8 inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[.15em] underline underline-offset-8">Get to know us <ArrowRight size={15}/></a></div></div></section>
    <section id="services" className="px-5 py-20 md:px-10 md:py-28"><div className="mb-12 flex items-end justify-between"><div><p className="mb-4 text-xs uppercase tracking-[.2em] text-copper">What we do</p><h2 className="display text-5xl md:text-7xl">The menu</h2></div><a href="#booking" className="hidden text-xs uppercase tracking-[.15em] underline underline-offset-8 md:block">All services</a></div><div className="grid border-t line md:grid-cols-2">{services.map(([name, desc, time, price]) => <div key={name} className="flex items-end justify-between gap-4 border-b line py-7"><div><h3 className="display text-2xl">{name}</h3><p className="mt-2 text-sm text-muted">{desc}</p><p className="mt-4 font-mono text-[11px] uppercase tracking-widest text-muted">{time}</p></div><div className="text-right"><p className="text-xl">{price}</p><button onClick={() => setBooking(true)} className="mt-4 text-[11px] uppercase tracking-widest text-copper underline underline-offset-4">Book</button></div></div>)}</div></section>
    <section id="barbers" className="paper px-5 py-20 md:px-10 md:py-28"><p className="mb-4 text-xs uppercase tracking-[.2em] text-copper">The people</p><h2 className="display mb-12 text-5xl md:text-7xl">Meet your barber</h2><div className="grid gap-x-6 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{barbers.map(([name, spec, bio], i) => <article key={name}><div className={`mb-5 aspect-[.78] bg-neutral-300 bg-cover bg-center grayscale ${i===0?'bg-[url(https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=700&q=80)':i===1?'bg-[url(https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=700&q=80)':i===2?'bg-[url(https://images.unsplash.com/photo-1619410291956-7d7c4f75b4c2?auto=format&fit=crop&w=700&q=80)]':'bg-[url(https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=700&q=80)]'}`}></div><p className="text-[10px] font-bold tracking-[.18em] text-copper">{spec}</p><h3 className="display mt-2 text-2xl">{name}</h3><p className="mt-3 text-sm leading-6 text-ink/65">{bio}</p></article>)}</div></section>
    <section id="story" className="grid md:grid-cols-2"><div className="min-h-[420px] bg-[url(https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=1200&q=85)] bg-cover bg-center"></div><div className="flex flex-col justify-center px-5 py-20 md:px-16"><p className="mb-5 text-xs uppercase tracking-[.2em] text-copper">Our story</p><h2 className="display text-5xl leading-none md:text-7xl">Made for<br/><em>the in-between.</em></h2><p className="mt-8 max-w-md leading-7 text-paper/65">The space between work and dinner. Between who you were and who you are becoming. We opened CUT / THRU because the best barbershops have always been more than a service — they are part of a city’s rhythm.</p></div></section>
    <section className="paper px-5 py-20 md:px-10 md:py-28"><div className="grid gap-12 md:grid-cols-3">{testimonials.map(([quote, by]) => <figure key={by} className="border-t border-ink/20 pt-6"><blockquote className="display text-2xl leading-tight">{quote}</blockquote><figcaption className="mt-7 text-[10px] font-bold tracking-[.18em] text-copper">{by}</figcaption></figure>)}</div></section>
    <section id="visit" className="grid paper md:grid-cols-2"><div className="p-5 py-20 md:p-16"><p className="mb-5 text-xs uppercase tracking-[.2em] text-copper">Find us</p><h2 className="display text-5xl md:text-7xl">Come through.</h2><div className="mt-12 grid gap-8 text-sm md:grid-cols-2"><div><p className="mb-2 text-xs font-bold uppercase tracking-widest text-ink/45">Address</p><p>Wibautstraat 131-D<br/>1091 GL Amsterdam</p><a className="mt-3 inline-block underline" href="https://maps.google.com">Get directions <ArrowRight size={14} className="inline"/></a></div><div><p className="mb-2 text-xs font-bold uppercase tracking-widest text-ink/45">Opening hours</p><p>Tue—Fri · 09:00—19:00<br/>Sat · 09:00—17:00<br/>Sun—Mon · Closed</p></div></div></div><div className="min-h-[330px] bg-[#d8d1c3] p-5 text-ink/50 md:p-10"><div className="flex h-full items-end justify-between border border-ink/20 p-5"><span className="text-xs uppercase tracking-widest">52.3549° N, 4.9156° E</span><MapPin/></div></div></section>
    <section className="px-5 py-24 text-center md:py-36"><p className="mb-5 text-xs uppercase tracking-[.2em] text-copper">Ready when you are</p><h2 className="display mx-auto max-w-3xl text-6xl leading-[.9] md:text-8xl">Leave sharper<br/><em>than you arrived.</em></h2><button onClick={() => setBooking(true)} className="mt-10 inline-flex items-center gap-8 bg-copper px-6 py-4 text-xs font-bold uppercase tracking-[.15em] text-ink">Book an appointment <CalendarDays size={16}/></button></section>
    <footer className="flex flex-col justify-between gap-8 border-t line px-5 py-8 text-xs text-muted md:flex-row md:px-10"><p className="font-bold tracking-[.2em] text-paper">CUT / THRU</p><p>Wibautstraat 131-D · Amsterdam</p><div className="flex gap-5"><a href="tel:+31203334455"><Phone size={15}/></a><a href="#top" aria-label="Back to top">Top</a><a href="mailto:hello@cutthru.amsterdam">hello@cutthru.amsterdam</a></div></footer>
    {booking && <div className="fixed inset-0 z-30 flex items-end justify-center bg-ink/80 p-0 backdrop-blur-sm md:items-center md:p-6"><div role="dialog" aria-modal="true" aria-labelledby="booking-title" className="paper w-full max-w-lg p-6 md:p-10">{sent ? <div className="py-10 text-center"><p className="text-xs uppercase tracking-widest text-copper">You’re all set</p><h2 className="display mt-4 text-5xl">See you in the chair.</h2><p className="mt-5 text-sm text-ink/65">Your booking reference is <strong>CT-2408</strong>.</p><button onClick={() => {setBooking(false);setSent(false)}} className="mt-8 border border-ink px-5 py-3 text-xs uppercase tracking-widest">Close</button></div> : <form onSubmit={(e) => {e.preventDefault();setSent(true)}}><div className="flex justify-between"><div><p className="text-xs uppercase tracking-widest text-copper">Quick booking</p><h2 id="booking-title" className="display mt-2 text-4xl">Reserve your chair.</h2></div><button type="button" aria-label="Close booking" onClick={() => setBooking(false)}><X/></button></div><label className="mt-8 block text-xs uppercase tracking-widest">Service<select required className="mt-2 block w-full border border-ink/30 bg-transparent p-3 text-sm"><option>The Signature Cut — €48</option><option>Cut & Beard — €62</option><option>The Classic Shave — €38</option></select></label><label className="mt-5 block text-xs uppercase tracking-widest">Your name<input required className="mt-2 block w-full border border-ink/30 bg-transparent p-3 text-sm" placeholder="Alex Morgan"/></label><label className="mt-5 block text-xs uppercase tracking-widest">Email<input required type="email" className="mt-2 block w-full border border-ink/30 bg-transparent p-3 text-sm" placeholder="alex@example.com"/></label><button className="mt-8 w-full bg-ink px-5 py-4 text-xs font-bold uppercase tracking-widest text-paper">Continue to availability <ArrowRight className="ml-2 inline" size={15}/></button></form>}</div></div>}
  </main>
}
